//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.9.0
// 	protoc               v5.29.3
// source: pipe_plugin.proto

package plugin

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
	_ "unsafe"
)

const PipePluginPluginAPIVersion = 1

//go:wasmexport pipe_plugin_api_version
func _pipe_plugin_api_version() uint64 {
	return PipePluginPluginAPIVersion
}

var pipePlugin PipePlugin

func RegisterPipePlugin(p PipePlugin) {
	pipePlugin = p
}

//go:wasmexport pipe_plugin_get_info
func _pipe_plugin_get_info(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(InfoRequest)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := pipePlugin.GetInfo(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport pipe_plugin_execute
func _pipe_plugin_execute(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(ExecuteRequest)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := pipePlugin.Execute(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

type pipeHost struct{}

func NewPipeHost() PipeHost {
	return pipeHost{}
}

//go:wasmimport env execute_stats
func _execute_stats(ptr uint32, size uint32) uint64

func (h pipeHost) ExecuteStats(ctx context.Context, request *StatsExecuteRequest) (*StatsExecuteResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _execute_stats(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(StatsExecuteResponse)
	if err = response.UnmarshalVT(buf); err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport env execute_search
func _execute_search(ptr uint32, size uint32) uint64

func (h pipeHost) ExecuteSearch(ctx context.Context, request *SearchExecuteRequest) (*SearchExecuteResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _execute_search(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(SearchExecuteResponse)
	if err = response.UnmarshalVT(buf); err != nil {
		return nil, err
	}
	return response, nil
}
