// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v7.35.0
// source: pipe_plugin.proto

package plugin

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The pipe keywords this plugin handles, e.g. ["chart"].
	Commands []string `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

// A page of raw log entries produced by a search stage.
type LogResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Each entry encoded as a JSON object matching the frontend's LogEntry shape.
	EntriesJson []string `protobuf:"bytes,1,rep,name=entries_json,json=entriesJson,proto3" json:"entries_json,omitempty"`
	TotalCount  int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *LogResult) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LogResult) GetEntriesJson() []string {
	if x != nil {
		return x.EntriesJson
	}
	return nil
}

func (x *LogResult) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// A stats table produced by an aggregation stage.
type StatsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	GroupBy []string `protobuf:"bytes,2,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	// Each row encoded as a JSON array, e.g. ["200", 1048576].
	RowsJson    []string `protobuf:"bytes,3,rep,name=rows_json,json=rowsJson,proto3" json:"rows_json,omitempty"`
	IsAggregate bool     `protobuf:"varint,4,opt,name=is_aggregate,json=isAggregate,proto3" json:"is_aggregate,omitempty"`
	TotalCount  int32    `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Optional rendering hint set by a downstream plugin, e.g. "pie", "bar", "line".
	ChartType string `protobuf:"bytes,6,opt,name=chart_type,json=chartType,proto3" json:"chart_type,omitempty"`
}

func (x *StatsResult) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *StatsResult) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *StatsResult) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *StatsResult) GetRowsJson() []string {
	if x != nil {
		return x.RowsJson
	}
	return nil
}

func (x *StatsResult) GetIsAggregate() bool {
	if x != nil {
		return x.IsAggregate
	}
	return false
}

func (x *StatsResult) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *StatsResult) GetChartType() string {
	if x != nil {
		return x.ChartType
	}
	return ""
}

// The typed value that flows between pipe stages.
type PipelineValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*PipelineValue_Logs
	//	*PipelineValue_Stats
	Value isPipelineValue_Value `protobuf_oneof:"value"`
}

func (x *PipelineValue) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (m *PipelineValue) GetValue() isPipelineValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *PipelineValue) GetLogs() *LogResult {
	if x, ok := x.GetValue().(*PipelineValue_Logs); ok {
		return x.Logs
	}
	return nil
}

func (x *PipelineValue) GetStats() *StatsResult {
	if x, ok := x.GetValue().(*PipelineValue_Stats); ok {
		return x.Stats
	}
	return nil
}

type isPipelineValue_Value interface {
	isPipelineValue_Value()
}

type PipelineValue_Logs struct {
	Logs *LogResult `protobuf:"bytes,1,opt,name=logs,proto3,oneof"`
}

type PipelineValue_Stats struct {
	Stats *StatsResult `protobuf:"bytes,2,opt,name=stats,proto3,oneof"`
}

func (*PipelineValue_Logs) isPipelineValue_Value() {}

func (*PipelineValue_Stats) isPipelineValue_Value() {}

type ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The matched command keyword, e.g. "chart".
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Everything after the command keyword on the same pipe segment, e.g. "bar".
	Args string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	// Deprecated: use input instead. Kept for backward compatibility.
	Rest         string   `protobuf:"bytes,3,opt,name=rest,proto3" json:"rest,omitempty"`
	ParquetPaths []string `protobuf:"bytes,4,rep,name=parquet_paths,json=parquetPaths,proto3" json:"parquet_paths,omitempty"`
	WhereClause  string   `protobuf:"bytes,5,opt,name=where_clause,json=whereClause,proto3" json:"where_clause,omitempty"`
	StartTime    string   `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime      string   `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Page         int32    `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     int32    `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Output of the previous pipe stage, or unset if this is the first stage.
	// When set, plugins should prefer this data over issuing their own queries.
	Input *PipelineValue `protobuf:"bytes,10,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *ExecuteRequest) GetRest() string {
	if x != nil {
		return x.Rest
	}
	return ""
}

func (x *ExecuteRequest) GetParquetPaths() []string {
	if x != nil {
		return x.ParquetPaths
	}
	return nil
}

func (x *ExecuteRequest) GetWhereClause() string {
	if x != nil {
		return x.WhereClause
	}
	return ""
}

func (x *ExecuteRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ExecuteRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ExecuteRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ExecuteRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ExecuteRequest) GetInput() *PipelineValue {
	if x != nil {
		return x.Input
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Typed output passed to the next stage, or rendered by the host when terminal.
	Output *PipelineValue `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetOutput() *PipelineValue {
	if x != nil {
		return x.Output
	}
	return nil
}

type StatsExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Stats expression string, e.g. "sum(bytes) BY status_code".
	StatsExpr    string   `protobuf:"bytes,1,opt,name=stats_expr,json=statsExpr,proto3" json:"stats_expr,omitempty"`
	ParquetPaths []string `protobuf:"bytes,2,rep,name=parquet_paths,json=parquetPaths,proto3" json:"parquet_paths,omitempty"`
	WhereClause  string   `protobuf:"bytes,3,opt,name=where_clause,json=whereClause,proto3" json:"where_clause,omitempty"`
	Page         int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     int32    `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *StatsExecuteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *StatsExecuteRequest) GetStatsExpr() string {
	if x != nil {
		return x.StatsExpr
	}
	return ""
}

func (x *StatsExecuteRequest) GetParquetPaths() []string {
	if x != nil {
		return x.ParquetPaths
	}
	return nil
}

func (x *StatsExecuteRequest) GetWhereClause() string {
	if x != nil {
		return x.WhereClause
	}
	return ""
}

func (x *StatsExecuteRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *StatsExecuteRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParquetPaths []string `protobuf:"bytes,1,rep,name=parquet_paths,json=parquetPaths,proto3" json:"parquet_paths,omitempty"`
	WhereClause  string   `protobuf:"bytes,2,opt,name=where_clause,json=whereClause,proto3" json:"where_clause,omitempty"`
	Page         int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     int32    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *SearchExecuteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SearchExecuteRequest) GetParquetPaths() []string {
	if x != nil {
		return x.ParquetPaths
	}
	return nil
}

func (x *SearchExecuteRequest) GetWhereClause() string {
	if x != nil {
		return x.WhereClause
	}
	return ""
}

func (x *SearchExecuteRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchExecuteRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Each log entry encoded as a JSON object matching the frontend's LogEntry shape.
	EntriesJson []string `protobuf:"bytes,1,rep,name=entries_json,json=entriesJson,proto3" json:"entries_json,omitempty"`
	TotalCount  int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Error       string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SearchExecuteResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SearchExecuteResponse) GetEntriesJson() []string {
	if x != nil {
		return x.EntriesJson
	}
	return nil
}

func (x *SearchExecuteResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatsExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	GroupBy []string `protobuf:"bytes,2,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	// Each row encoded as a JSON array, e.g. `["200", 1048576]`.
	RowsJson    []string `protobuf:"bytes,3,rep,name=rows_json,json=rowsJson,proto3" json:"rows_json,omitempty"`
	IsAggregate bool     `protobuf:"varint,4,opt,name=is_aggregate,json=isAggregate,proto3" json:"is_aggregate,omitempty"`
	TotalCount  int32    `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Error       string   `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *StatsExecuteResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *StatsExecuteResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *StatsExecuteResponse) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *StatsExecuteResponse) GetRowsJson() []string {
	if x != nil {
		return x.RowsJson
	}
	return nil
}

func (x *StatsExecuteResponse) GetIsAggregate() bool {
	if x != nil {
		return x.IsAggregate
	}
	return false
}

func (x *StatsExecuteResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *StatsExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// go:plugin type=plugin version=1
type PipePlugin interface {
	// Returns plugin metadata including which pipe commands it handles.
	GetInfo(context.Context, *InfoRequest) (*InfoResponse, error)
	// Execute a pipe command. The host calls this after parsing the query.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

// go:plugin type=host
type PipeHost interface {
	// Execute a stats expression over parquet files. The plugin calls this
	// to delegate the actual DuckDB query execution to the host.
	ExecuteStats(context.Context, *StatsExecuteRequest) (*StatsExecuteResponse, error)
	// Execute a raw log entry search over parquet files. Returns one page of
	// entries matching the where clause, encoded as JSON objects.
	ExecuteSearch(context.Context, *SearchExecuteRequest) (*SearchExecuteResponse, error)
}
